// <auto-generated />
using BlazorIA.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorIA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527183508_TablaPersonas")]
    partial class TablaPersonas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("BlazorIA.Entidades.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "felipe.gavilan@example.com",
                            Nombre = "Felipe Gavilán",
                            Salario = 45000m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "maria.lopez@example.com",
                            Nombre = "María López",
                            Salario = 52000m
                        },
                        new
                        {
                            Id = 3,
                            Activo = false,
                            Email = "carlos.rodriguez@example.com",
                            Nombre = "Carlos Rodríguez",
                            Salario = 61000m
                        },
                        new
                        {
                            Id = 4,
                            Activo = false,
                            Email = "ana.martinez@example.com",
                            Nombre = "Ana Martínez",
                            Salario = 48000m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Email = "luis.gomez@example.com",
                            Nombre = "Luis Gómez",
                            Salario = 55000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
